enum CurrencyTypes {
  // converter
  GET_CURRENCY = 'GET_CURRENCY',
  GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS',
  GET_CURRENCY_ERROR = 'GET_CURRENCY_ERROR',

  // latest rate
  GET_LATEST_RATE = 'GET_LATEST_RATE',
  GET_LATEST_RATE_SUCCESS = 'GET_LATEST_RATE_SUCCESS',
  GET_LATEST_RATE_ERROR = 'GET_LATEST_RATE_ERROR',

}
export default CurrencyTypes;
